image: node:lts

before_script:
  - npm install -g @apidevtools/swagger-cli
  - npm install -g @stoplight/spectral-cli
  - npm install -g anypoint-cli-v4
  - export ANYPOINT_CLIENT_ID=6fd1624df84648248a2d21d999e7bc60
  - export ANYPOINT_CLIENT_SECRET=d308968217D24B879db0e2d0e3794398
  - export ANYPOINT_ORG=a9a32236-77e1-4d8b-baaf-22ff5a53b7f1
  - export GROUP_ID=a9a32236-77e1-4d8b-baaf-22ff5a53b7f1

stages:
  - deploy

build-job:       # This job runs in the deploy stage
  stage: deploy
  script:
    - MAIN_FILE=$(echo "$CI_PROJECT_NAME" | sed -e "s/-spec/.yaml/g") #get main file name in variable
    - BUNDLE_FILE=$(echo "$CI_PROJECT_NAME" | sed -e "s/-spec/-bundle.json/g") #get bundle file name in variable
    - MAIN_JSON_FILE=$(echo "$CI_PROJECT_NAME" | sed -e "s/-spec/.json/g") #get bundle file name in variable
    - echo "$MAIN_JSON_FILE"
    - ASSET_NAME=$(echo "$CI_PROJECT_NAME" | sed -e "s/-spec//g")
    - swagger-cli bundle "$MAIN_FILE" -o "$BUNDLE_FILE" #build oas 3 json bundle file
    - swagger-cli bundle "$BUNDLE_FILE" -o "$MAIN_JSON_FILE" #build oas 3 json oas file
    - spectral lint $MAIN_FILE --ruleset ruleset/myruleset.yaml #check oas file with rules
    #- curl --location --request POST "https://anypoint.mulesoft.com/accounts/login" --header "Content-Type:application/json" --header "Accept:application/json" --data-raw '{"username":"samy_toubal", "password":"Anypoint1Password@2"}' > token.txt
    #- cat $MAIN_FILE | grep -A3 'version:' sample-api.yaml | tail -n1
    - API_VERSION=$(grep -A0 'version:' $MAIN_FILE | tail -n1 | awk '{ print $2}')
    - ls -ax
    #| python3 -c "import sys, json; print(json.load(sys.stdin)['info'])" > token.txt
    - MAIN_FILE_REQUEST=$(echo "{\"mainFile\":\"$MAIN_JSON_FILE\"}")
    - FILE_REQUEST=$(echo "{\"oas.json\":\"$MAIN_JSON_FILE\"}")
    - echo "$MAIN_FILE_REQUEST"
    - echo "$FILE_REQUEST"
    #- anypoint-cli-v4 account:environment:list
    - anypoint-cli-v4 exchange:asset:upload --name "OAS Asset" --description "OAS" --properties=$MAIN_FILE_REQUEST --files=$FILE_REQUEST $GROUP_ID/$ASSET_NAME/$API_VERSION


   