image: node:lts

before_script:
  - npm install -g @apidevtools/swagger-cli
  - npm install -g @stoplight/spectral-cli
  - npm install -g anypoint-cli-v4
  - anypoint-cli-v4 conf username samy_toubal
  - anypoint-cli-v4 conf password Anypoint1Password@2
  - anypoint-cli-v4 conf organization a9a32236-77e1-4d8b-baaf-22ff5a53b7f1

stages:
  - deploy

build-job:       # This job runs in the deploy stage
  stage: deploy
  script:
    - MAIN_FILE=$(echo "$CI_PROJECT_NAME" | sed -e "s/-spec/.yaml/g") #get main file name in variable
    - BUNDLE_FILE=$(echo "$CI_PROJECT_NAME" | sed -e "s/-spec/-bundle.yaml/g") #get bundle file name in variable
    - swagger-cli bundle "$MAIN_FILE" -o "$BUNDLE_FILE" #build oas 3 json bundle file
    - spectral lint $MAIN_FILE --ruleset ruleset/myruleset.yaml #check oas file with rules
    #- curl --location --request POST "https://anypoint.mulesoft.com/accounts/login" --header "Content-Type:application/json" --header "Accept:application/json" --data-raw '{"username":"samy_toubal", "password":"Anypoint1Password@2"}' > token.txt
    #- cat token.txt | python3 -c "import sys, json; print(json.load(sys.stdin)['body']['request'])" > token.txt
    #- cat token.txt