image: node:lts

before_script:
  - npm install -g @apidevtools/swagger-cli
  - npm install -g @stoplight/spectral-cli

stages:
  - build

build-job:
  stage: build
  script:
    - MAIN_FILE=$(echo "$CI_PROJECT_NAME" | sed -e "s/-spec/.yaml/g")
    - BUNDLE_FILE=$(echo "$CI_PROJECT_NAME" | sed -e "s/-spec/-bundle.yaml/g")
    - echo "$MAIN_FILE"
    - echo "$BUNDLE_FILE"
    - swagger-cli bundle "$MAIN_FILE" -o "$BUNDLE_FILE"
    - ls -ax
    - spectral lint sample-api.yaml --ruleset ruleset/myruleset.yaml > result.txt
    - ls -ax
    - echo "FINISHED"